module.exports = {
  addindex: require(__dirname + '/function/addindex'),
  compose: require('./function/compose'),
  curry: require('./function/curry'),
  identity: require('./function/identity'),
  always: require('./function/always'),
  invoker: require('./function/invoker'),

  append: require('./list/append'),
  prepend: require('./list/prepend'),
  byIndex: require('./list/by-index'),
  concat: require('./list/concat'),
  contains: require('./list/contains'),
  filter: require('./list/filter'),
  find: require('./list/find'),
  flatten: require('./list/flatten'),
  head: require('./list/head'),
  init: require('./list/init'),
  map: require('./list/map'),
  pluck: require('./list/pluck'),
  reduce: require('./list/reduce'),
  reject: require('./list/reject'),
  remove: require('./list/remove'),
  reverse: require('./list/reverse'),
  tail: require('./list/tail'),
  tap: require('./list/tap'),
  times: require('./list/times'),
  update: require('./list/update'),

  and: require('./logic/and'),
  or: require('./logic/or'),
  not: require('./logic/not'),
  ifElse: require('./logic/ifElse'),

  add: require('./math/add'),
  divide: require('./math/divide'),
  mean: require('./math/mean'),
  multiply: require('./math/multiply'),
  product: require('./math/product'),
  subtract: require('./math/subtract'),
  sum: require('./math/sum'),

  assoc: require('./object/assoc'),
  assocPath: require('./object/assoc-path'),
  has: require('./object/has'),
  keys: require('./object/keys'),
  lens: require('./object/lens'),
  lensPath: require('./object/lens-path'),
  lensProp: require('./object/lens-prop'),
  over: require('./object/over'),
  path: require('./object/path'),
  pathOr: require('./object/path-or'),
  prop: require('./object/prop'),
  propOr: require('./object/prop-or'),
  set: require('./object/set'),
  view: require('./object/view'),

  equals: require('./relation/equals'),
  gt: require('./relation/gt'),
  gte: require('./relation/gte'),
  lt: require('./relation/lt'),

  split: require('./string/split'),

  is: require('./type/is'),
  isArray: require('./type/is-array'),
  isNil: require('./type/is-nil')
}
